# Generated by Django 4.2.30 on 2026-06-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
